server {
    listen 80;

    location /api/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /flask/ {
        proxy_pass http://flask_service:5000/;
    }

    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}